name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake for PotentialMap
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}/PotentialMap
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}/PotentialMap

    - name: Build PotentialMap
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}/PotentialMap --config ${{ matrix.build_type }}

    - name: Test PotentialMap
      working-directory: ${{ steps.strings.outputs.build-output-dir }}/PotentialMap
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Configure CMake for SFPS
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}/SFPS
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}/SFPS

    - name: Build SFPS
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}/SFPS --config ${{ matrix.build_type }}

    - name: Test SFPS
      working-directory: ${{ steps.strings.outputs.build-output-dir }}/SFPS
      run: ctest --build-config ${{ matrix.build_type }}
